learner         :       DERPP 
optim           :       AdamW
learning_rate   :       0.0005
momentum        :       0.9
weight_decay    :       0.0001
dataset         :       cifar100
n_classes       :       100
n_tasks         :       10
mem_size        :       1000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       inc
seed            :       0
derpp_alpha     :       0.2
derpp_beta      :       1.0
tf_type         :       partial

